manifest:
  remotes:
    - name: luerl21
      url-base: https://github.com/luerl21
    - name: steno
      url-base: https://github.com/dnaq/
  projects:
    - name: zmk
      remote: luerl21
      revision: main
      import: app/west.yml
  self:
    path: config
